docs(readme): update readme
nervosnetwork/mercury pull request #293
Opened 2021-11-12 10:42 UTC by rev-chaos

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Which docs this PR relation**:

Ref #

**Which toolchain this PR adaption**:

No Breaking Change

**Special notes for your reviewer**:

2021-11-14 04:10 UTC, KaoImin requested changes

2021-11-14 04:10 UTC, KaoImin commented on README.md
> +#### Recommended Hardware
```suggestion
#### Minimum Hardware
```
```suggestion
#### Recommended Hardware
```

2021-11-14 14:06 UTC, KaoImin approved these changes

2021-11-15 13:46 UTC, rev-chaos commented on README.md
> +2 Cores - 4G Memory - 50G Disk and above.
```suggestion
4 Cores - 8G Memory - 500G Disk and above.

If you use a standalone server to run the Postgre server, then 50G Disk is enough. 
```

2021-11-15 13:46 UTC, rev-chaos commented on README.md
> +2 Cores - 4G Memory - 50G Disk and above.
```suggestion
4 Cores - 8G Memory - 500G Disk and above.
```

2021-11-15 13:47 UTC, merged