fix(sync): reduce the memory usage in synchronization
nervosnetwork/mercury pull request #389
Opened 2022-03-08 06:14 UTC by KaoImin

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Which docs this PR relation**:

Ref #

**Which toolchain this PR adaption**:

No Breaking Change

**Special notes for your reviewer**:

2022-03-08 11:02 UTC, quake requested changes

2022-03-08 11:02 UTC, quake commented on core/synchronization/src/task.rs
> +    // let mut status_list = Vec::new();
please remove commented out code

2022-03-08 11:02 UTC, quake commented on core/synchronization/src/task.rs
> +    // status_list.extend(sub_task.iter().map(|num| SyncStatus::new(*num)));
please remove commented out code

2022-03-10 02:13 UTC, EthanYuan commented on core/cli/src/lib.rs
> +                .do_sync(self.config.sync_config.sync_block_batch_size)
The do_sync method accepts a max_task_number parameter, but passes the sync_block_batch_size parameter.

2022-03-14 05:06 UTC, quake approved these changes

2022-03-26 05:03 UTC, quake commented on core/synchronization/src/lib.rs
> +        for id in (0..self.chain_tip).step_by(TASK_LEN as usize) {
should be `=self.chain_tip` ?
```suggestion
        for id in (0..=self.chain_tip).step_by(TASK_LEN as usize) {
```

2022-03-30 00:06 UTC, EthanYuan approved these changes

2022-03-30 00:07 UTC, merged